In [108]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [109]:
df1 = pd.read_csv('train_info.csv')
df2 = pd.read_csv('train_schedule.csv')

In [110]:
df1

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,PUNE-TGN EMU,PUNE JN.,TALEGAON,Tuesday
11109,99905,EMU,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,EMU,PUNE JN.,TALEGAON,Wednesday
11111,99907,EMU,TALEGAON,PUNE JN.,Thursday
11112,99908,EMU,PUNE JN.,TALEGAON,Sunday

In [111]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 11113 entries, 0 to 11112
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Train_No                  11113 non-null  int64
 1   Train_Name                11113 non-null  str
 2   Source_Station_Name       11113 non-null  str
 3   Destination_Station_Name  11113 non-null  str
 4   days                      11113 non-null  str
dtypes: int64(1), str(4)
memory usage: 434.2 KB

In [112]:
df1.isnull().sum()

Train_No                    0
Train_Name                  0
Source_Station_Name         0
Destination_Station_Name    0
days                        0
dtype: int64

In [113]:
df1.duplicated().sum()

np.int64(0)

In [114]:
df1.columns = df1.columns.str.lower()

In [115]:
df1

,train_no,train_name,source_station_name,destination_station_name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,PUNE-TGN EMU,PUNE JN.,TALEGAON,Tuesday
11109,99905,EMU,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,EMU,PUNE JN.,TALEGAON,Wednesday
11111,99907,EMU,TALEGAON,PUNE JN.,Thursday
11112,99908,EMU,PUNE JN.,TALEGAON,Sunday

In [116]:
df1.train_name = df1.train_name.str.title()

In [117]:
df1

,train_no,train_name,source_station_name,destination_station_name,days
0,107,Swv-Mao-Vlnk,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,Vlnk-Mao-Swv,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,Mao-Kop Spec,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,Palace On Wh,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,Bsb Bharatda,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,Pune-Tgn Emu,PUNE JN.,TALEGAON,Tuesday
11109,99905,Emu,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,Emu,PUNE JN.,TALEGAON,Wednesday
11111,99907,Emu,TALEGAON,PUNE JN.,Thursday
11112,99908,Emu,PUNE JN.,TALEGAON,Sunday

In [118]:
df1.source_station_name = df1.source_station_name.str.replace({'.':''})
df1.source_station_name = df1.source_station_name.str.title()

In [119]:
df1

,train_no,train_name,source_station_name,destination_station_name,days
0,107,Swv-Mao-Vlnk,Sawantwadi Road,MADGOAN JN.,Saturday
1,108,Vlnk-Mao-Swv,Madgoan Jn,SAWANTWADI ROAD,Friday
2,128,Mao-Kop Spec,Madgoan Jn,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,Palace On Wh,Delhi-Safdar Jang,DELHI-SAFDAR JANG,Wednesday
4,401,Bsb Bharatda,Aurangabad,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,Pune-Tgn Emu,Pune Jn,TALEGAON,Tuesday
11109,99905,Emu,Talegaon,SHIVAJINAGAR,Monday
11110,99906,Emu,Pune Jn,TALEGAON,Wednesday
11111,99907,Emu,Talegaon,PUNE JN.,Thursday
11112,99908,Emu,Pune Jn,TALEGAON,Sunday

In [120]:
df1.destination_station_name = df1.destination_station_name.str.replace({'.':''})
df1.destination_station_name = df1.destination_station_name.str.title()

In [121]:
df1

,train_no,train_name,source_station_name,destination_station_name,days
0,107,Swv-Mao-Vlnk,Sawantwadi Road,Madgoan Jn,Saturday
1,108,Vlnk-Mao-Swv,Madgoan Jn,Sawantwadi Road,Friday
2,128,Mao-Kop Spec,Madgoan Jn,Chhatrapati Shahu Maharaj Terminus,Friday
3,290,Palace On Wh,Delhi-Safdar Jang,Delhi-Safdar Jang,Wednesday
4,401,Bsb Bharatda,Aurangabad,Varanasi Jn,Saturday
...,...,...,...,...,...
11108,99904,Pune-Tgn Emu,Pune Jn,Talegaon,Tuesday
11109,99905,Emu,Talegaon,Shivajinagar,Monday
11110,99906,Emu,Pune Jn,Talegaon,Wednesday
11111,99907,Emu,Talegaon,Pune Jn,Thursday
11112,99908,Emu,Pune Jn,Talegaon,Sunday

In [122]:
df2

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655

In [123]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 186074 entries, 0 to 186073
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   SN              186074 non-null  int64
 1   Train_No        186074 non-null  int64
 2   Station_Code    186074 non-null  str
 3   1A              186074 non-null  int64
 4   2A              186074 non-null  int64
 5   3A              186074 non-null  int64
 6   SL              186074 non-null  int64
 7   Station_Name    186074 non-null  str
 8   Route_Number    186074 non-null  int64
 9   Arrival_time    186074 non-null  str
 10  Departure_Time  186074 non-null  str
 11  Distance        186074 non-null  int64
dtypes: int64(8), str(4)
memory usage: 17.0 MB

In [124]:
df2.isnull().sum()

SN                0
Train_No          0
Station_Code      0
1A                0
2A                0
3A                0
SL                0
Station_Name      0
Route_Number      0
Arrival_time      0
Departure_Time    0
Distance          0
dtype: int64

In [125]:
df2.drop(columns='SN',inplace=True)

In [126]:
df2

,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...
186069,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0
186070,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199
186071,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312
186072,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577
186073,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655

In [127]:
df2.columns = df2.columns.str.lower()

In [128]:
df2

,train_no,station_code,1a,2a,3a,sl,station_name,route_number,arrival_time,departure_time,distance
0,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...
186069,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0
186070,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199
186071,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312
186072,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577
186073,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655

In [129]:
df2.arrival_time = pd.to_datetime(df2.arrival_time,errors='coerce').dt.time
df2.departure_time = pd.to_datetime(df2.departure_time,errors='coerce').dt.time

C:\Users\Tonmoy Dey\AppData\Local\Temp\ipykernel_16576\2809190277.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2.arrival_time = pd.to_datetime(df2.arrival_time,errors='coerce').dt.time
C:\Users\Tonmoy Dey\AppData\Local\Temp\ipykernel_16576\2809190277.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2.departure_time = pd.to_datetime(df2.departure_time,errors='coerce').dt.time

In [130]:
df2

,train_no,station_code,1a,2a,3a,sl,station_name,route_number,arrival_time,departure_time,distance
0,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...
186069,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0
186070,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199
186071,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312
186072,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577
186073,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655

In [131]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 186074 entries, 0 to 186073
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   train_no        186074 non-null  int64
 1   station_code    186074 non-null  str
 2   1a              186074 non-null  int64
 3   2a              186074 non-null  int64
 4   3a              186074 non-null  int64
 5   sl              186074 non-null  int64
 6   station_name    186074 non-null  str
 7   route_number    186074 non-null  int64
 8   arrival_time    186074 non-null  object
 9   departure_time  186074 non-null  object
 10  distance        186074 non-null  int64
dtypes: int64(7), object(2), str(2)
memory usage: 15.6+ MB

In [132]:
df2

,train_no,station_code,1a,2a,3a,sl,station_name,route_number,arrival_time,departure_time,distance
0,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...
186069,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0
186070,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199
186071,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312
186072,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577
186073,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655

In [133]:
df2.station_name = df2.station_name.str.title()

In [134]:
df2

,train_no,station_code,1a,2a,3a,sl,station_name,route_number,arrival_time,departure_time,distance
0,107,SWV,100,100,100,100,Sawantwadi R,1,00:00:00,10:25:00,0
1,107,THVM,260,228,196,164,Thivim,1,11:06:00,11:08:00,32
2,107,KRMI,345,296,247,198,Karmali,1,11:28:00,11:30:00,49
3,107,MAO,490,412,334,256,Madgoan Jn.,1,12:10:00,00:00:00,78
4,108,MAO,100,100,100,100,Madgoan Jn.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...
186069,22439,NDLS,100,100,100,100,New Delhi,1,00:00:00,06:00:00,0
186070,22439,UMB,1095,896,697,1095,Ambala Cant Jn,1,08:08:00,08:10:00,199
186071,22439,LDH,1660,1348,1036,1660,Ludhiana Jn,1,09:19:00,09:21:00,312
186072,22439,JAT,2985,2408,1831,2985,Jammu Tawi,1,12:38:00,12:40:00,577
186073,22439,SVDK,3375,2720,2065,3375,Shmata Vd Katra,1,14:00:00,00:00:00,655

In [135]:
df2.station_name = df2.station_name.str.replace({'.':''})

In [136]:
df2

,train_no,station_code,1a,2a,3a,sl,station_name,route_number,arrival_time,departure_time,distance
0,107,SWV,100,100,100,100,Sawantwadi R,1,00:00:00,10:25:00,0
1,107,THVM,260,228,196,164,Thivim,1,11:06:00,11:08:00,32
2,107,KRMI,345,296,247,198,Karmali,1,11:28:00,11:30:00,49
3,107,MAO,490,412,334,256,Madgoan Jn,1,12:10:00,00:00:00,78
4,108,MAO,100,100,100,100,Madgoan Jn,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...
186069,22439,NDLS,100,100,100,100,New Delhi,1,00:00:00,06:00:00,0
186070,22439,UMB,1095,896,697,1095,Ambala Cant Jn,1,08:08:00,08:10:00,199
186071,22439,LDH,1660,1348,1036,1660,Ludhiana Jn,1,09:19:00,09:21:00,312
186072,22439,JAT,2985,2408,1831,2985,Jammu Tawi,1,12:38:00,12:40:00,577
186073,22439,SVDK,3375,2720,2065,3375,Shmata Vd Katra,1,14:00:00,00:00:00,655

In [137]:
df1

,train_no,train_name,source_station_name,destination_station_name,days
0,107,Swv-Mao-Vlnk,Sawantwadi Road,Madgoan Jn,Saturday
1,108,Vlnk-Mao-Swv,Madgoan Jn,Sawantwadi Road,Friday
2,128,Mao-Kop Spec,Madgoan Jn,Chhatrapati Shahu Maharaj Terminus,Friday
3,290,Palace On Wh,Delhi-Safdar Jang,Delhi-Safdar Jang,Wednesday
4,401,Bsb Bharatda,Aurangabad,Varanasi Jn,Saturday
...,...,...,...,...,...
11108,99904,Pune-Tgn Emu,Pune Jn,Talegaon,Tuesday
11109,99905,Emu,Talegaon,Shivajinagar,Monday
11110,99906,Emu,Pune Jn,Talegaon,Wednesday
11111,99907,Emu,Talegaon,Pune Jn,Thursday
11112,99908,Emu,Pune Jn,Talegaon,Sunday

In [138]:
df1.days.unique()

<StringArray>
[  'Saturday',     'Friday',  'Wednesday',    'Tuesday',     'Monday',
     'Sunday',   'Thursday',    'Mondayd',  'Thursdayd',   'Tuesdayd',
    'Fridayd', 'Wednesdayd',  'Saturdayd',    'Sundayd']
Length: 14, dtype: str

In [139]:
df1.days = df1.days.replace({'Mondayd':'Monday','Thursdayd':'Thursday','Tuesdayd':'Tuesday','Fridayd':'Friday','Wednesdayd':'Wednesday','Saturdayd':'Saturday','Sundayd':'Sunday'})

In [140]:
df1.days.unique()

<StringArray>
['Saturday', 'Friday', 'Wednesday', 'Tuesday', 'Monday', 'Sunday', 'Thursday']
Length: 7, dtype: str

In [141]:
df2.duplicated().sum()

np.int64(0)

In [142]:
engine = create_engine('mysql+pymysql://root:1234@localhost/indian_railways_db')

In [143]:
df1.to_sql(name='train_info',con=engine,if_exists='replace',index=False)
df2.to_sql(name='train_schedule',con=engine,if_exists='replace',index=False)

186074