In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('financial_loan.csv')

In [3]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,11-02-2021,13-09-2021,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,01-01-2021,14-12-2021,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,05-01-2021,12-12-2021,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,25-02-2021,12-12-2021,12-03-2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,01-01-2021,14-12-2021,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,INDIVIDUAL,< 1 year,Joseph M Sanzari Company,C,MORTGAGE,11-07-2021,16-05-2021,16-05-2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,INDIVIDUAL,8 years,Swat Fame,C,RENT,11-10-2021,16-04-2021,16-05-2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,INDIVIDUAL,5 years,Anaheim Regional Medical Center,D,RENT,11-09-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,INDIVIDUAL,5 years,Brooklyn Radiology,D,RENT,11-10-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,INDIVIDUAL,4 years,Allen Edmonds,F,RENT,11-07-2021,16-05-2021,16-05-2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  str
 2   application_type       38576 non-null  str
 3   emp_length             38576 non-null  str
 4   emp_title              37138 non-null  str
 5   grade                  38576 non-null  str
 6   home_ownership         38576 non-null  str
 7   issue_date             38576 non-null  str
 8   last_credit_pull_date  38576 non-null  str
 9   last_payment_date      38576 non-null  str
 10  loan_status            38576 non-null  str
 11  next_payment_date      38576 non-null  str
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  str
 14  sub_grade              38576 non-null  str
 15  term                   38576 non-null  str
 16  verification_status    38576 non-null  str
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: float64(4), int64(5), str(15)
memory usage: 7.1 MB

In [6]:
df.shape

(38576, 24)

In [7]:
df.isnull().sum()

id                          0
address_state               0
application_type            0
emp_length                  0
emp_title                1438
grade                       0
home_ownership              0
issue_date                  0
last_credit_pull_date       0
last_payment_date           0
loan_status                 0
next_payment_date           0
member_id                   0
purpose                     0
sub_grade                   0
term                        0
verification_status         0
annual_income               0
dti                         0
installment                 0
int_rate                    0
loan_amount                 0
total_acc                   0
total_payment               0
dtype: int64

In [9]:
df.emp_title

0                                  Ryder
1                         MKC Accounting
2                  Chemat Technology Inc
3                    barnes distribution
4                          J&J Steel Inc
                      ...
38571           Joseph M Sanzari Company
38572                          Swat Fame
38573    Anaheim Regional Medical Center
38574                 Brooklyn Radiology
38575                      Allen Edmonds
Name: emp_title, Length: 38576, dtype: str

In [10]:
df.emp_title = df.emp_title.str.title()

In [12]:
df.dropna(subset='emp_title',inplace=True)

In [13]:
df.isnull().sum()

id                       0
address_state            0
application_type         0
emp_length               0
emp_title                0
grade                    0
home_ownership           0
issue_date               0
last_credit_pull_date    0
last_payment_date        0
loan_status              0
next_payment_date        0
member_id                0
purpose                  0
sub_grade                0
term                     0
verification_status      0
annual_income            0
dti                      0
installment              0
int_rate                 0
loan_amount              0
total_acc                0
total_payment            0
dtype: int64

In [14]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,11-02-2021,13-09-2021,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,Mkc Accounting,E,RENT,01-01-2021,14-12-2021,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,05-01-2021,12-12-2021,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,Barnes Distribution,B,MORTGAGE,25-02-2021,12-12-2021,12-03-2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,01-01-2021,14-12-2021,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,INDIVIDUAL,< 1 year,Joseph M Sanzari Company,C,MORTGAGE,11-07-2021,16-05-2021,16-05-2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,INDIVIDUAL,8 years,Swat Fame,C,RENT,11-10-2021,16-04-2021,16-05-2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,INDIVIDUAL,5 years,Anaheim Regional Medical Center,D,RENT,11-09-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,INDIVIDUAL,5 years,Brooklyn Radiology,D,RENT,11-10-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,INDIVIDUAL,4 years,Allen Edmonds,F,RENT,11-07-2021,16-05-2021,16-05-2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [16]:
df.application_type = df.application_type.str.title()

In [20]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,Individual,< 1 year,Ryder,C,RENT,11-02-2021,13-09-2021,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,Individual,9 years,Mkc Accounting,E,RENT,01-01-2021,14-12-2021,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,Individual,4 years,Chemat Technology Inc,C,RENT,05-01-2021,12-12-2021,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,Individual,< 1 year,Barnes Distribution,B,MORTGAGE,25-02-2021,12-12-2021,12-03-2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,Individual,10+ years,J&J Steel Inc,A,MORTGAGE,01-01-2021,14-12-2021,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,Individual,< 1 year,Joseph M Sanzari Company,C,MORTGAGE,11-07-2021,16-05-2021,16-05-2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,Individual,8 years,Swat Fame,C,RENT,11-10-2021,16-04-2021,16-05-2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,Individual,5 years,Anaheim Regional Medical Center,D,RENT,11-09-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,Individual,5 years,Brooklyn Radiology,D,RENT,11-10-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,Individual,4 years,Allen Edmonds,F,RENT,11-07-2021,16-05-2021,16-05-2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [21]:
df.emp_length.unique()

<StringArray>
[ '< 1 year',   '9 years',   '4 years', '10+ years',   '3 years',   '5 years',
    '1 year',   '6 years',   '2 years',   '7 years',   '8 years']
Length: 11, dtype: str

In [22]:
df.emp_length = df.emp_length.replace({
                                    '< 1 year':'Less that 1 year',
                                    '10+ years':'More than 10 years'
})

In [23]:
df.emp_length.unique()

<StringArray>
[  'Less that 1 year',            '9 years',            '4 years',
 'More than 10 years',            '3 years',            '5 years',
             '1 year',            '6 years',            '2 years',
            '7 years',            '8 years']
Length: 11, dtype: str

In [24]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,Individual,Less that 1 year,Ryder,C,RENT,11-02-2021,13-09-2021,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,Individual,9 years,Mkc Accounting,E,RENT,01-01-2021,14-12-2021,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,Individual,4 years,Chemat Technology Inc,C,RENT,05-01-2021,12-12-2021,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,Individual,Less that 1 year,Barnes Distribution,B,MORTGAGE,25-02-2021,12-12-2021,12-03-2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,Individual,More than 10 years,J&J Steel Inc,A,MORTGAGE,01-01-2021,14-12-2021,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,Individual,Less that 1 year,Joseph M Sanzari Company,C,MORTGAGE,11-07-2021,16-05-2021,16-05-2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,Individual,8 years,Swat Fame,C,RENT,11-10-2021,16-04-2021,16-05-2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,Individual,5 years,Anaheim Regional Medical Center,D,RENT,11-09-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,Individual,5 years,Brooklyn Radiology,D,RENT,11-10-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,Individual,4 years,Allen Edmonds,F,RENT,11-07-2021,16-05-2021,16-05-2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [25]:
df.home_ownership = df.home_ownership.str.title()

In [27]:
df.issue_date = pd.to_datetime(df.issue_date, errors='coerce')

In [28]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,Individual,Less that 1 year,Ryder,C,Rent,2021-11-02,13-09-2021,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,Individual,9 years,Mkc Accounting,E,Rent,2021-01-01,14-12-2021,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,Individual,4 years,Chemat Technology Inc,C,Rent,2021-05-01,12-12-2021,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,Individual,Less that 1 year,Barnes Distribution,B,Mortgage,NaT,12-12-2021,12-03-2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,Individual,More than 10 years,J&J Steel Inc,A,Mortgage,2021-01-01,14-12-2021,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,Individual,Less that 1 year,Joseph M Sanzari Company,C,Mortgage,2021-11-07,16-05-2021,16-05-2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,Individual,8 years,Swat Fame,C,Rent,2021-11-10,16-04-2021,16-05-2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,Individual,5 years,Anaheim Regional Medical Center,D,Rent,2021-11-09,16-05-2021,16-05-2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,Individual,5 years,Brooklyn Radiology,D,Rent,2021-11-10,16-05-2021,16-05-2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,Individual,4 years,Allen Edmonds,F,Rent,2021-11-07,16-05-2021,16-05-2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [29]:
df.issue_date.isnull().sum()

np.int64(4)

In [30]:
df.dropna(subset='issue_date',inplace=True)

In [31]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,Individual,Less that 1 year,Ryder,C,Rent,2021-11-02,13-09-2021,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,Individual,9 years,Mkc Accounting,E,Rent,2021-01-01,14-12-2021,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,Individual,4 years,Chemat Technology Inc,C,Rent,2021-05-01,12-12-2021,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
4,1068350,IL,Individual,More than 10 years,J&J Steel Inc,A,Mortgage,2021-01-01,14-12-2021,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
7,1066424,PA,Individual,More than 10 years,Sci Mahanoy,A,Own,2021-11-06,14-07-2021,14-07-2021,...,A4,36 months,Source Verified,59000.0,0.0665,172.10,0.0790,5500,23,6172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,Individual,Less that 1 year,Joseph M Sanzari Company,C,Mortgage,2021-11-07,16-05-2021,16-05-2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,Individual,8 years,Swat Fame,C,Rent,2021-11-10,16-04-2021,16-05-2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,Individual,5 years,Anaheim Regional Medical Center,D,Rent,2021-11-09,16-05-2021,16-05-2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,Individual,5 years,Brooklyn Radiology,D,Rent,2021-11-10,16-05-2021,16-05-2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,Individual,4 years,Allen Edmonds,F,Rent,2021-11-07,16-05-2021,16-05-2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [32]:
df.last_credit_pull_date = pd.to_datetime(df.issue_date, errors='coerce')

In [33]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,Individual,Less that 1 year,Ryder,C,Rent,2021-11-02,2021-11-02,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,Individual,9 years,Mkc Accounting,E,Rent,2021-01-01,2021-01-01,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,Individual,4 years,Chemat Technology Inc,C,Rent,2021-05-01,2021-05-01,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
4,1068350,IL,Individual,More than 10 years,J&J Steel Inc,A,Mortgage,2021-01-01,2021-01-01,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
7,1066424,PA,Individual,More than 10 years,Sci Mahanoy,A,Own,2021-11-06,2021-11-06,14-07-2021,...,A4,36 months,Source Verified,59000.0,0.0665,172.10,0.0790,5500,23,6172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,Individual,Less that 1 year,Joseph M Sanzari Company,C,Mortgage,2021-11-07,2021-11-07,16-05-2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,Individual,8 years,Swat Fame,C,Rent,2021-11-10,2021-11-10,16-05-2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,Individual,5 years,Anaheim Regional Medical Center,D,Rent,2021-11-09,2021-11-09,16-05-2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,Individual,5 years,Brooklyn Radiology,D,Rent,2021-11-10,2021-11-10,16-05-2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,Individual,4 years,Allen Edmonds,F,Rent,2021-11-07,2021-11-07,16-05-2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [34]:
df.last_credit_pull_date.isnull().sum()

np.int64(0)

In [35]:
df.last_payment_date = pd.to_datetime(df.issue_date, errors='coerce')

In [36]:
df.last_payment_date.isnull().sum()

np.int64(0)

In [37]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,Individual,Less that 1 year,Ryder,C,Rent,2021-11-02,2021-11-02,2021-11-02,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,Individual,9 years,Mkc Accounting,E,Rent,2021-01-01,2021-01-01,2021-01-01,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,Individual,4 years,Chemat Technology Inc,C,Rent,2021-05-01,2021-05-01,2021-05-01,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
4,1068350,IL,Individual,More than 10 years,J&J Steel Inc,A,Mortgage,2021-01-01,2021-01-01,2021-01-01,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
7,1066424,PA,Individual,More than 10 years,Sci Mahanoy,A,Own,2021-11-06,2021-11-06,2021-11-06,...,A4,36 months,Source Verified,59000.0,0.0665,172.10,0.0790,5500,23,6172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,Individual,Less that 1 year,Joseph M Sanzari Company,C,Mortgage,2021-11-07,2021-11-07,2021-11-07,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,Individual,8 years,Swat Fame,C,Rent,2021-11-10,2021-11-10,2021-11-10,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,Individual,5 years,Anaheim Regional Medical Center,D,Rent,2021-11-09,2021-11-09,2021-11-09,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,Individual,5 years,Brooklyn Radiology,D,Rent,2021-11-10,2021-11-10,2021-11-10,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,Individual,4 years,Allen Edmonds,F,Rent,2021-11-07,2021-11-07,2021-11-07,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [38]:
df.next_payment_date = pd.to_datetime(df.issue_date, errors='coerce')

In [39]:
df.next_payment_date.isnull().sum()

np.int64(0)

In [40]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,Individual,Less that 1 year,Ryder,C,Rent,2021-11-02,2021-11-02,2021-11-02,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,Individual,9 years,Mkc Accounting,E,Rent,2021-01-01,2021-01-01,2021-01-01,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,Individual,4 years,Chemat Technology Inc,C,Rent,2021-05-01,2021-05-01,2021-05-01,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
4,1068350,IL,Individual,More than 10 years,J&J Steel Inc,A,Mortgage,2021-01-01,2021-01-01,2021-01-01,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
7,1066424,PA,Individual,More than 10 years,Sci Mahanoy,A,Own,2021-11-06,2021-11-06,2021-11-06,...,A4,36 months,Source Verified,59000.0,0.0665,172.10,0.0790,5500,23,6172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,Individual,Less that 1 year,Joseph M Sanzari Company,C,Mortgage,2021-11-07,2021-11-07,2021-11-07,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,Individual,8 years,Swat Fame,C,Rent,2021-11-10,2021-11-10,2021-11-10,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,Individual,5 years,Anaheim Regional Medical Center,D,Rent,2021-11-09,2021-11-09,2021-11-09,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,Individual,5 years,Brooklyn Radiology,D,Rent,2021-11-10,2021-11-10,2021-11-10,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,Individual,4 years,Allen Edmonds,F,Rent,2021-11-07,2021-11-07,2021-11-07,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [41]:
df.purpose = df.purpose.str.title()

In [42]:
df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,Individual,Less that 1 year,Ryder,C,Rent,2021-11-02,2021-11-02,2021-11-02,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,Individual,9 years,Mkc Accounting,E,Rent,2021-01-01,2021-01-01,2021-01-01,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,Individual,4 years,Chemat Technology Inc,C,Rent,2021-05-01,2021-05-01,2021-05-01,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
4,1068350,IL,Individual,More than 10 years,J&J Steel Inc,A,Mortgage,2021-01-01,2021-01-01,2021-01-01,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
7,1066424,PA,Individual,More than 10 years,Sci Mahanoy,A,Own,2021-11-06,2021-11-06,2021-11-06,...,A4,36 months,Source Verified,59000.0,0.0665,172.10,0.0790,5500,23,6172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,Individual,Less that 1 year,Joseph M Sanzari Company,C,Mortgage,2021-11-07,2021-11-07,2021-11-07,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,Individual,8 years,Swat Fame,C,Rent,2021-11-10,2021-11-10,2021-11-10,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,Individual,5 years,Anaheim Regional Medical Center,D,Rent,2021-11-09,2021-11-09,2021-11-09,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,Individual,5 years,Brooklyn Radiology,D,Rent,2021-11-10,2021-11-10,2021-11-10,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,Individual,4 years,Allen Edmonds,F,Rent,2021-11-07,2021-11-07,2021-11-07,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679