# Working on Real Project with Python

## (A part of Big Data Analysis)

***

# Cars Dataset
***
Here, 
The data of different cars is given with their specifications.


This data is available as a CSV file. We are going to analyze this data set using the Pandas DataFrame.

----

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [22]:
df = pd.read_csv('2. Cars Data1.csv')

In [23]:
df

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

In [24]:
df.columns = df.columns.str.lower()

1) Instruction ( For Data Cleaning ) 
- Find all Null Value in the dataset. If there is any null value in any column, then fill it with the mean of that column.

In [25]:
df.isnull().sum()

make           4
model          4
type           4
origin         4
drivetrain     4
msrp           4
invoice        4
enginesize     4
cylinders      6
horsepower     4
mpg_city       4
mpg_highway    4
weight         4
wheelbase      4
length         4
dtype: int64

In [33]:
df.make = df.make.fillna(df.make.mode()[0])

In [46]:
df.model = df.model.fillna(df.model.mode()[0])
df.type = df.type.fillna(df.type.mode()[0])
df.origin = df.origin.fillna(df.origin.mode()[0])
df.drivetrain = df.drivetrain.fillna(df.drivetrain.mode()[0])
df.msrp =df.msrp.fillna(df.msrp.mode()[0])
df.invoice =df.invoice.fillna(df.invoice.mode()[0])
df.enginesize =df.enginesize.fillna(df.enginesize.mode()[0])
df.cylinders =df.cylinders.fillna(df.cylinders.mode()[0])
df.horsepower =df.horsepower.fillna(df.horsepower.mode()[0])
df.mpg_city =df.mpg_city.fillna(df.mpg_city.mode()[0])
df.mpg_highway =df.mpg_highway.fillna(df.mpg_highway.mode()[0])
df.weight =df.weight.fillna(df.weight.mode()[0])
df.wheelbase =df.wheelbase.fillna(df.wheelbase.mode()[0])
df.length =df.length.fillna(df.length.mode()[0])

In [47]:
df.isnull().sum()

make           0
model          0
type           0
origin         0
drivetrain     0
msrp           0
invoice        0
enginesize     0
cylinders      0
horsepower     0
mpg_city       0
mpg_highway    0
weight         0
wheelbase      0
length         0
dtype: int64

----

2) Question ( Based on Value Counts )
- Check what are the different types of Make are there in our dataset. And, what is the count (occurrence) of each Make in the data
?

In [50]:
counts = df.make.value_counts()

----

3) Instruction ( Filtering )
- Show all the records where Origin is Asia or Europe.

In [59]:
df[(df.origin == 'Asia') | (df.origin == 'Europe')]

,make,model,type,origin,drivetrain,msrp,invoice,enginesize,cylinders,horsepower,mpg_city,mpg_highway,weight,wheelbase,length
0,Acura,MDX,SUV,Asia,Asia,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Asia,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Asia,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Asia,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Asia,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Europe,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Europe,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Europe,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Europe,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,Europe,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

281

----

4) Instruction ( Removing unwanted records )
- Remove all the records (rows) where Weight is above 4000.

In [67]:
df.drop(df[df.weight > 4000].index,inplace=True)

In [68]:
df

,make,model,type,origin,drivetrain,msrp,invoice,enginesize,cylinders,horsepower,mpg_city,mpg_highway,weight,wheelbase,length
1,Acura,RSX Type S 2dr,Sedan,Asia,Asia,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Asia,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Asia,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Asia,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Asia,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Europe,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Europe,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Europe,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Europe,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,Europe,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

-----

5) Instruction ( Applying function on a column )
- Increase all the values of 'MPG_City' column by 3.

In [72]:
df.mpg_city = df.mpg_city.apply(lambda x:x+3)

In [73]:
df

,make,model,type,origin,drivetrain,msrp,invoice,enginesize,cylinders,horsepower,mpg_city,mpg_highway,weight,wheelbase,length
1,Acura,RSX Type S 2dr,Sedan,Asia,Asia,"$23,820","$21,761",2.0,4.0,200.0,27.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Asia,"$26,990","$24,647",2.4,4.0,200.0,25.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Asia,"$33,195","$30,299",3.2,6.0,270.0,23.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Asia,"$43,755","$39,014",3.5,6.0,225.0,21.0,24.0,3880.0,115.0,197.0
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Asia,"$46,100","$41,100",3.5,6.0,225.0,21.0,24.0,3893.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Europe,"$40,565","$38,203",2.4,5.0,197.0,24.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Europe,"$42,565","$40,083",2.3,5.0,242.0,23.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Europe,"$45,210","$42,573",2.9,6.0,268.0,22.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Europe,"$26,135","$24,641",1.9,4.0,170.0,25.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,Europe,"$35,145","$33,112",2.5,5.0,208.0,23.0,27.0,3823.0,109.0,186.0

----

----

-----

----