# Working on Real Project with Python on 'COVID-19 Dataset'

## (A part of Big Data Analysis)

----

# COVID-19 SMALL DATASET

-----

We have taken a small dataset of Covid-19, just for your understaning purpose. You have to work on the original dataset which contains about 19000 rows.

The data used here is till 29-April-2020 and has records as on 29-April-2020.

This data is available as a CSV file, downloaded from Kaggle.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('4. Covid_19_data.csv')

In [3]:
df

          Date     State          Region  Confirmed  Deaths  Recovered
0    4/29/2020       NaN     Afghanistan       1939      60        252
1    4/29/2020       NaN         Albania        766      30        455
2    4/29/2020       NaN         Algeria       3848     444       1702
3    4/29/2020       NaN         Andorra        743      42        423
4    4/29/2020       NaN          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[321 rows x 6 columns]

In [4]:
df.columns = df.columns.str.lower()

In [5]:
df

          date     state          region  confirmed  deaths  recovered
0    4/29/2020       NaN     Afghanistan       1939      60        252
1    4/29/2020       NaN         Albania        766      30        455
2    4/29/2020       NaN         Algeria       3848     444       1702
3    4/29/2020       NaN         Andorra        743      42        423
4    4/29/2020       NaN          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[321 rows x 6 columns]

In [7]:
df.isnull().sum() * 100 / len(df)

date          0.000000
state        56.386293
region        0.000000
confirmed     0.000000
deaths        0.000000
recovered     0.000000
dtype: float64

In [8]:
df.state = df.state.fillna('Unknown')

In [9]:
df

          date     state          region  confirmed  deaths  recovered
0    4/29/2020   Unknown     Afghanistan       1939      60        252
1    4/29/2020   Unknown         Albania        766      30        455
2    4/29/2020   Unknown         Algeria       3848     444       1702
3    4/29/2020   Unknown         Andorra        743      42        423
4    4/29/2020   Unknown          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[321 rows x 6 columns]

In [18]:
df.duplicated().sum()

np.int64(0)

We will analyze this data using the Pandas DataFrame.

### Q.1 ) Show the number of Confirmed , Deaths and Recovered cases in each Region.

In [16]:
df.groupby('region')[['confirmed','deaths','recovered']].sum()

                    confirmed  deaths  recovered
region
Afghanistan              1939      60        252
Albania                   766      30        455
Algeria                  3848     444       1702
Andorra                   743      42        423
Angola                     27       2          7
...                       ...     ...        ...
West Bank and Gaza        344       2         71
Western Sahara              6       0          5
Yemen                       6       0          1
Zambia                     97       3         54
Zimbabwe                   32       4          5

[187 rows x 3 columns]

### Q2) Remove all the records where Confirmed Cases is Less Than 10.

In [ ]:
df = df.drop(df[df.confirmed < 10].index)

In [21]:
df

          date     state          region  confirmed  deaths  recovered
0    4/29/2020   Unknown     Afghanistan       1939      60        252
1    4/29/2020   Unknown         Albania        766      30        455
2    4/29/2020   Unknown         Algeria       3848     444       1702
3    4/29/2020   Unknown         Andorra        743      42        423
4    4/29/2020   Unknown          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[304 rows x 6 columns]

### Q.3) In which Region, maximum number of Confirmed cases were recorded ?

In [31]:
df.groupby('region')['confirmed'].sum().sort_values(ascending = False)

region
US            1039909
Spain          236899
Italy          203591
France         166536
UK             166432
               ...
Seychelles         11
Burundi            11
Suriname           10
Gambia             10
Holy See           10
Name: confirmed, Length: 180, dtype: int64

### Q.4) In which Region, minimum number of Deaths cases were recorded ?

In [ ]:
df.groupby('region').deaths.min().sort_values()

region
Denmark           0
Eritrea           0
Mongolia          0
Cambodia          0
Mozambique        0
              ...
Iran           5957
Germany        6467
Belgium        7501
Spain         24275
Italy         27682
Name: deaths, Length: 180, dtype: int64

### Q.5) How many Confirmed , Deaths & Recovered cases were reported from India till 29 April 2020 ?

In [ ]:
df.groupby('region')

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 304 entries, 0 to 320
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       304 non-null    datetime64[ns]
 1   state      304 non-null    object
 2   region     304 non-null    object
 3   confirmed  304 non-null    int64
 4   deaths     304 non-null    int64
 5   recovered  304 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 16.6+ KB

### Q. 6-A ) Sort the entire data wrt No. of Confirmed cases in ascending order.

In [45]:
df.sort_values(by = ['confirmed'])

          date      state    region  confirmed  deaths  recovered
156 2020-04-29    Unknown  Suriname         10       1          8
70  2020-04-29    Unknown  Holy See         10       0          2
59  2020-04-29    Unknown    Gambia         10       1          8
318 2020-04-29      Yukon    Canada         11       0          0
217 2020-04-29  Greenland   Denmark         11       0         11
..         ...        ...       ...        ...     ...        ...
57  2020-04-29    Unknown    France     165093   24087      48228
168 2020-04-29    Unknown        UK     165221   26097          0
80  2020-04-29    Unknown     Italy     203591   27682      71252
153 2020-04-29    Unknown     Spain     236899   24275     132929
265 2020-04-29   New York        US     299691   23477          0

[304 rows x 6 columns]

### Q. 6-B ) Sort the entire data wrt No. of Recovered cases in descending order.

In [44]:
df.recovered.sort_values()

199         0
276         0
116         0
246         0
277         0
        ...
229     63616
80      71252
76      73791
61     120400
153    132929
Name: recovered, Length: 304, dtype: int64