In [46]:
import pandas as pd
from sqlalchemy import create_engine

In [47]:
df = pd.read_csv('tourism_data.csv')

In [48]:
df

,Continent,Country,CountryJoin,Month,Seasons,State,Way In,Year,Count,GDP,Population
0,Europe,Austria,Austria,January,Winter,Amazonas,Land,2009,4.0,30000.0,8192880.0
1,Europe,Denmark,Denmark,January,Winter,Amazonas,Land,2009,2.0,31100.0,5450661.0
2,Europe,Switzerland,Switzerland,January,Winter,Amazonas,Land,2009,15.0,32700.0,7523934.0
3,Europe,Norway,Norway,January,Winter,Amazonas,Land,2009,0.0,37800.0,4610820.0
4,Europe,Other countries,NaN,January,Winter,Mato Grosso do Sul,Land,2009,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
247279,Europe,Poland,Poland,August,Summer,Acre,River,2015,0.0,11100.0,38536869.0
247280,Europe,Hungary,Hungary,August,Summer,Acre,River,2015,0.0,13900.0,9981334.0
247281,Europe,Czech Republic,Czech Republic,August,Summer,Acre,River,2015,0.0,15700.0,10235455.0
247282,Europe,Portugal,Portugal,August,Summer,Acre,River,2015,0.0,18000.0,10605870.0
247283,Europe,Greece,Greece,August,Summer,Acre,River,2015,0.0,20000.0,10688058.0

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 247284 entries, 0 to 247283
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Continent    247284 non-null  str
 1   Country      247284 non-null  str
 2   CountryJoin  214848 non-null  str
 3   Month        247284 non-null  str
 4   Seasons      247284 non-null  str
 5   State        247284 non-null  str
 6   Way In       247284 non-null  str
 7   Year         247284 non-null  int64
 8   Count        245364 non-null  float64
 9   GDP          214848 non-null  float64
 10  Population   214848 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 20.8 MB

In [50]:
df.isnull().sum()

Continent          0
Country            0
CountryJoin    32436
Month              0
Seasons            0
State              0
Way In             0
Year               0
Count           1920
GDP            32436
Population     32436
dtype: int64

In [51]:
df.columns = df.columns.str.lower()

In [52]:
df.isnull().sum()

continent          0
country            0
countryjoin    32436
month              0
seasons            0
state              0
way in             0
year               0
count           1920
gdp            32436
population     32436
dtype: int64

In [53]:
df.drop(columns='countryjoin',inplace=True)

In [54]:
df.isnull().sum()

continent         0
country           0
month             0
seasons           0
state             0
way in            0
year              0
count          1920
gdp           32436
population    32436
dtype: int64

In [55]:
df.drop(columns='count',inplace=True)

In [56]:
df.gdp = df.gdp.fillna(df.gdp.median())
df.population = df.population.fillna(df.population.median())

In [57]:
df

,continent,country,month,seasons,state,way in,year,gdp,population
0,Europe,Austria,January,Winter,Amazonas,Land,2009,30000.0,8192880.0
1,Europe,Denmark,January,Winter,Amazonas,Land,2009,31100.0,5450661.0
2,Europe,Switzerland,January,Winter,Amazonas,Land,2009,32700.0,7523934.0
3,Europe,Norway,January,Winter,Amazonas,Land,2009,37800.0,4610820.0
4,Europe,Other countries,January,Winter,Mato Grosso do Sul,Land,2009,13900.0,12127071.0
...,...,...,...,...,...,...,...,...,...
247279,Europe,Poland,August,Summer,Acre,River,2015,11100.0,38536869.0
247280,Europe,Hungary,August,Summer,Acre,River,2015,13900.0,9981334.0
247281,Europe,Czech Republic,August,Summer,Acre,River,2015,15700.0,10235455.0
247282,Europe,Portugal,August,Summer,Acre,River,2015,18000.0,10605870.0
247283,Europe,Greece,August,Summer,Acre,River,2015,20000.0,10688058.0

In [58]:
df.duplicated().sum()

np.int64(768)

In [59]:
df.drop_duplicates(inplace=True)

In [60]:
df

,continent,country,month,seasons,state,way in,year,gdp,population
0,Europe,Austria,January,Winter,Amazonas,Land,2009,30000.0,8192880.0
1,Europe,Denmark,January,Winter,Amazonas,Land,2009,31100.0,5450661.0
2,Europe,Switzerland,January,Winter,Amazonas,Land,2009,32700.0,7523934.0
3,Europe,Norway,January,Winter,Amazonas,Land,2009,37800.0,4610820.0
4,Europe,Other countries,January,Winter,Mato Grosso do Sul,Land,2009,13900.0,12127071.0
...,...,...,...,...,...,...,...,...,...
247279,Europe,Poland,August,Summer,Acre,River,2015,11100.0,38536869.0
247280,Europe,Hungary,August,Summer,Acre,River,2015,13900.0,9981334.0
247281,Europe,Czech Republic,August,Summer,Acre,River,2015,15700.0,10235455.0
247282,Europe,Portugal,August,Summer,Acre,River,2015,18000.0,10605870.0
247283,Europe,Greece,August,Summer,Acre,River,2015,20000.0,10688058.0

In [61]:
df = df.rename(columns={'way in':'way_in'})

In [62]:
df

,continent,country,month,seasons,state,way_in,year,gdp,population
0,Europe,Austria,January,Winter,Amazonas,Land,2009,30000.0,8192880.0
1,Europe,Denmark,January,Winter,Amazonas,Land,2009,31100.0,5450661.0
2,Europe,Switzerland,January,Winter,Amazonas,Land,2009,32700.0,7523934.0
3,Europe,Norway,January,Winter,Amazonas,Land,2009,37800.0,4610820.0
4,Europe,Other countries,January,Winter,Mato Grosso do Sul,Land,2009,13900.0,12127071.0
...,...,...,...,...,...,...,...,...,...
247279,Europe,Poland,August,Summer,Acre,River,2015,11100.0,38536869.0
247280,Europe,Hungary,August,Summer,Acre,River,2015,13900.0,9981334.0
247281,Europe,Czech Republic,August,Summer,Acre,River,2015,15700.0,10235455.0
247282,Europe,Portugal,August,Summer,Acre,River,2015,18000.0,10605870.0
247283,Europe,Greece,August,Summer,Acre,River,2015,20000.0,10688058.0

In [63]:
df.info()

<class 'pandas.DataFrame'>
Index: 246516 entries, 0 to 247283
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   continent   246516 non-null  str
 1   country     246516 non-null  str
 2   month       246516 non-null  str
 3   seasons     246516 non-null  str
 4   state       246516 non-null  str
 5   way_in      246516 non-null  str
 6   year        246516 non-null  int64
 7   gdp         246516 non-null  float64
 8   population  246516 non-null  float64
dtypes: float64(2), int64(1), str(6)
memory usage: 18.8 MB

In [64]:
engine = create_engine('mysql+pymysql://root:1234@localhost/tourismdb')

In [65]:
df.to_sql(name='tourism',con=engine,if_exists='replace',index=False)

246516